@CEMS.AuthService_HostAddress = https://cems-auth-service.azurewebsites.net

POST {{CEMS.AuthService_HostAddress}}/register/
Accept: application/json
Content-Type: application/json
{
    "first_name": "Aziz",
    "last_name": "Umarov",
    "email": "user@example.com",
    "phone_number": "1234",
    "login": "user@example.com",
    "password": "securepassword123"
}
###

POST {{CEMS.AuthService_HostAddress}}/login/
Accept: application/json
Content-Type: application/json
{
  "login": "user@example.com",
  "password": "securepassword123"
}

###
