// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CEMS.Dal.Models;

[Table("conference")]
public partial class Conference
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    public string Description { get; set; }

    [Required]
    [Column("logo")]
    [StringLength(255)]
    public string Logo { get; set; }

    [Required]
    [Column("background")]
    [StringLength(255)]
    public string Background { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Conference")]
    public virtual ICollection<Moderator> Moderators { get; set; } = new List<Moderator>();

    [InverseProperty("Conference")]
    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
}