// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CEMS.Dal.Models;

[Table("moderator")]
public partial class Moderator
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("user_id")]
    public Guid UserId { get; set; }

    [Column("conference_id")]
    public Guid ConferenceId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("ConferenceId")]
    [InverseProperty("Moderators")]
    public virtual Conference Conference { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Moderators")]
    public virtual User User { get; set; }
}