// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CEMS.Dal.Models;

[Table("session")]
public partial class Session
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("location")]
    [StringLength(255)]
    public string Location { get; set; }

    [Column("conference_id")]
    public Guid ConferenceId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("ConferenceId")]
    [InverseProperty("Sessions")]
    public virtual Conference Conference { get; set; }

    [InverseProperty("Session")]
    public virtual ICollection<Talk> Talks { get; set; } = new List<Talk>();
}