// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CEMS.Dal.Models;

[Table("talk")]
public partial class Talk
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("presentation")]
    public string Presentation { get; set; }

    [Column("scheduled_time", TypeName = "datetime")]
    public DateTime? ScheduledTime { get; set; }

    [Column("session_id")]
    public Guid SessionId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Talk")]
    public virtual ICollection<Attendee> Attendees { get; set; } = new List<Attendee>();

    [ForeignKey("SessionId")]
    [InverseProperty("Talks")]
    public virtual Session Session { get; set; }

    [InverseProperty("Talk")]
    public virtual ICollection<Speaker> Speakers { get; set; } = new List<Speaker>();
}