// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CEMS.Dal.Models;

[Table("user")]
public partial class User
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("first_name")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("last_name")]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [Column("phone_number")]
    [StringLength(50)]
    public string PhoneNumber { get; set; }

    [Required]
    [Column("login")]
    [StringLength(255)]
    public string Login { get; set; }

    [Required]
    [Column("password_hash")]
    [StringLength(255)]
    public string PasswordHash { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Attendee> Attendees { get; set; } = new List<Attendee>();

    [InverseProperty("User")]
    public virtual ICollection<Moderator> Moderators { get; set; } = new List<Moderator>();

    [InverseProperty("User")]
    public virtual ICollection<Speaker> Speakers { get; set; } = new List<Speaker>();

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}