name: Create Azure Resources
on: 
    workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID  }}    # set this to your Azure Subscription Id
    AZURE_RESOURCEGROUP_NAME: cemp-rg                      # set this to your preferred resource group name
    AZURE_WEBAPP_NAME: sampleApp-webappsql-gh-actions-unique                          # set this to your preferred web app name
    ASP_NAME: sampleApp-webappsql-gh-actions
    SQLSERVER_NAME: sample-app-webappsql-gh-actions-srv                          # set this to your preferred sql server name
    DATABASE_NAME: sample-app-webappsql-gh-actions-db                   # set this to your preferred sql database name
    SQLADMIN_LOGIN: ${{ secrets.SQLADMIN_LOGIN  }}                # Create a secret in your Github repo for the SQL Admin login name you want to use
    SQLADMIN_PASS: ${{ secrets.SQLADMIN_PASS  }}                 # Create a secret in your Github repo for the SQL Admin password you want to use


jobs:
    build-and-deploy-to-dev:
      runs-on: ubuntu-latest
      steps:

      - name: Azure Login with Federated Identity
        uses: azure/login@v1
        with:
          creds: ${{ secrets.cems_env_SPN }}

      # Deployment of template    
      - name: Deploy ARM Template resourcegroup
        uses: azure/arm-deploy@v1
        with:
          # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: centralus # Set this to your target region
          template: repo/CEMS/deployment/Templates/cems-resource-group.json  # Set this to the location of your template file
          parameters: repo/CEMS/deployment/Templates/cems-resource-group.parameters.json rgName=${{env.AZURE_RESOURCEGROUP_NAME}} #override rgName in parameters file


      # Deployment of template    
      - name: Deploy ARM Template resources
        uses: azure/arm-deploy@v1
        with:
          # You can change these environment variables for your configuration:   AZURE_SUBSCRIPTION_ID
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{env.AZURE_RESOURCEGROUP_NAME}}
          region: centralus # Set this to your target region
          template: repo/CEMS/deployment/Templates/azuredeploy.json  # Set this to the location of your template file
          parameters: repo/CEMS/deployment/Templates/azuredeploy.parameters.json sqlServerName=${{env.SQLSERVER_NAME}} databaseName=${{env.DATABASE_NAME}} sqlAdminLogin=${{env.SQLADMIN_LOGIN}} sqlAdminPass=${{env.SQLADMIN_PASS}} # Set this to the location of your parameters file
